### ISSUE TITLE
Import of LanguageDetectorBuilder failed

### ISSUE THREAD

**Issue by geritwagner** [pemistahl/lingua-py#30] opened 2022-04-08 08:58 UTC
When loading the LanguageDetectorBuilder as recommended in the readme, I received the following error:

from lingua import LanguageDetectorBuilder
...
ImportError: cannot import name 'LanguageDetectorBuilder' from 'lingua'

The following worked for me:

from lingua.builder import LanguageDetectorBuilder

**Comment by pemistahl** [comment] 2022-04-08 09:14
Hi Gerit, thanks for reaching out to me.

I'm not able to reproduce your problem. The import `from lingua import LanguageDetectorBuilder` works fine for me. Which Python version are you using? In which exact context are you trying to import the library? Without more information, I cannot help you.

**Comment by geritwagner** [comment] 2022-04-08 09:26
Hi Peter,

I am using Python 3.8.10 with lingua-language-detector==1.0.1. Not sure why it throws this error. The package setup seems to be ok...

**Comment by pemistahl** [comment] 2022-04-13 09:25
I close this issue now. There is not enough information to help you. If you get a clue what might be wrong, feel free to re-open this issue and provide your findings. Thank you.

**Closed by pemistahl** 2022-04-13 09:25 UTC

**Comment by Lv101Magikarp** [comment] 2023-11-10 10:45
I ran into this issue because somehow I had the `lingua` package installed at the same time as the desired `lingua-language-detector` package and python was importing the wrong one.
